# Build and push pipeline
# 1 Build the python_server image
# 2 Push to self hosted registry

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python36:
      python.version: '3.6'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r test-requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m unittest discover -v
    displayName: 'Unittest'

  #- task: Docker@2
  #  inputs:
  #    containerRegistry: 'DockerRegistry'
  #    repository: 'python_server'
  #    command: 'buildAndPush'
  #    Dockerfile: '**/Dockerfile'
  #    buildContext: '**'
  #    tags: 'latest'